//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourOfLesson
    {
        public decimal id { get; set; }
        public decimal NumOfLesson { get; set; }
        public string TheHour { get; set; }
    }
}
